name: htop
version: master
summary: interactive text-mode process viewer for Unix systems
description: |
  htop is an interactive system-monitor process-viewer. It is designed as an
  alternative to the Unix program top. It shows a frequently updated list of the
  processes running on a computer, normally ordered by the amount of CPU usage.

grade: devel
confinement: strict

apps:
  htop:
    command: htop

parts:
  htop:
    source: .
    plugin: autotools
    build-packages: [libncursesw5-dev]
